// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

type WaitingList struct {
	ID         int64
	Email      string
	Name       string
	Bio        *string
	Region     *string
	InsertedAt int64
	UpdatedAt  int64
}
